### list tasks
GET http://localhost:8080/tasks

### create task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "name": "Tarefa 2"
}

### update task
PUT http://localhost:8080/tasks/3
Content-Type: application/json

{
    "name": "Tarefa 1546"
}
